# Generated by Django 4.1.2 on 2022-10-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.TextField(max_length=1000)),
                ('Generos', models.TextField(max_length=30)),
                ('Ultimo_lanzamiento', models.TextField(max_length=30)),
                ('Popular_semana', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAnimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Estado', models.CharField(max_length=10)),
                ('Descripcion', models.TextField(max_length=1000)),
                ('Canciones', models.CharField(max_length=2000)),
                ('Artista_Esc', models.CharField(max_length=30)),
            ],
        ),
    ]
